### ISSUE TITLE
Create Atom plugin

### ISSUE THREAD

**Issue by benedfit** [benedfit/jade-lint#12]

**Comment by zyklus** [comment]
I just incorporated jade-lint into my linting package (that was previously using the jade compiler) https://atom.io/packages/linter-jade

**Comment by benedfit** [comment]
Awesome, thanks!

I'll get the documentation updated with a link to your package

**Comment by benedfit** [comment]
One thing to add, if you're not already using the 'inline' reporters, then please feel free to as it's should simplify any regex you might already be using

**Comment by zyklus** [comment]
Thanks, I'm using your objects directly (specifically `linter.checkString`), not a regex.  I don't exactly like what I'm doing because I'm including `jade-lint/lib/config-file`, so it's currently tied to the internal workings, but it's fine for now.
