### ISSUE TITLE
Create Vim plugin

### ISSUE THREAD

**Issue by benedfit** [benedfit/jade-lint#21]

**Comment by benjaminparnell** [comment]
@benedfit I can have a crack at this if you like?

**Comment by benedfit** [comment]
@benjaminparnell yes please, and if you wouldn't mind submitting a PR linking to it via the README it would be much appreciated

**Comment by balaclark** [comment]
:+1: @benjaminparnell you will earn unlimited nerd points if you get this done...

**Comment by benjaminparnell** [comment]
I have submitted a PR to scrooloose/syntastic. https://github.com/scrooloose/syntastic/pull/1536. Once that (hopefully) gets merged I will PR with installation instructions.

**Comment by balaclark** [comment]
:clap:

**Comment by balaclark** [comment]
I'm using 

```
{ "presets": "clock" }
```

and all is well
