### ISSUE TITLE
disallowImplicitDiv behaves controversially

### ISSUE THREAD

**Issue by gergelykovacs** [benedfit/jade-lint#37]
"Avoid writing div when it would otherwise be implicit." 

According to the documentation it should be `disallowExpliciteDiv` or `requireImplicitDiv`.

Correctly `disallowImplicitDiv` (forcing to use `div`)

Actually the name and behavior is controversial.

**Comment by benedfit** [comment]
I did struggle with naming this one, and you're right that if I'm providing a rule that disallows it, I should also provide an inverse rule that requires it. I'll come up with a better name for these rules and a description of what they do
